### ISSUE TITLE
Metrics for alarms, "executionsTimeOut", cannot be used on AWS

### ISSUE THREAD

**Issue by yuu999** [serverless-operations/serverless-step-functions#305]
## Description
Even if I defined a metric name with `executionsTimeOut` as in the [README](https://github.com/serverless-operations/serverless-step-functions#cloudwatch-alarms) when defining the alarm, it was not reflected on AWS.    
In AWS, the timeout metric is defined as `ExecutionsTimedOut`. timed, not time. [aws](https://docs.aws.amazon.com/step-functions/latest/dg/procedure-cw-metrics.html)

Therefore, I think you need to change the code below to 'ExecutionsTimedOut'.  
please check it.

https://github.com/serverless-operations/serverless-step-functions/blob/01e7765842e39f60d04371975e303b2cb90423e7/lib/deploy/stepFunctions/compileAlarms.js#L9

**Comment by horike37** [comment]
@yuu999 
Thank you for reporting. Can you share your whole serverless.yml you use so that we can take a look at it?

**Comment by theburningmonk** [comment]
@yuu999 well caught, that's a typo on my side, will put a fix together

**Comment by yuu999** [comment]
@theburningmonk  
Thank you for fixing! We will continue to use this wonderful plugin. And, we will contact you if I find some problem again.

@horike37  
Tank you for replying.  
I'm sorry. I cannot share my serverless.yml yet because it's under development. But my code about the alarm is same to the README of this plugin.
