### ISSUE TITLE
Can't create CloudWatch Event with custom role to trigger StepFunction

### ISSUE THREAD

**Issue by bucha09** [serverless-operations/serverless-step-functions#306]
# Bug Report

## Description
1. Trying to create step function triggered by cloudwatch event (pattern) with custom event role 
2. Create new role, but it should attach existing one 
3. It won't attach existing role to event (To state machine existing role attached correctly)
Here is my serverless.yml
```
stepFunctions:
  stateMachines:
    myStateMachines:
      role: "arn:aws:iam::#{AWS::AccountId}:role/StepFunctions-Role"
      name: myStateMachines-${opt:stage}
      events:
        - cloudwatchEvent:
            name: PipelineChanges-${opt:stage}
            iamRole: "arn:aws:iam::#{AWS::AccountId}:role/Events-InvokeStepFunctions-Role"
            event:
              source:
                - "aws.codepipeline"
              detail-type:
                - "CodePipeline Action Execution State Change"
              detail:
                state:
                  - FAILED
                  - SUCCEEDED
                pipeline:
                  - MyServer-${opt:stage}
                action:
                  - ApproveSWAP
                type:
                  category:
                    - Approval
            enabled: true
      definition:
      ....
```
Creates everything correctly except Cloudwatch event, is it possible to attach existing role to custom event?

**Comment by horike37** [comment]
CloudWatch Event does not support for custom role at the moment. But would be great if it will be introduced.

**Comment by bucha09** [comment]
![Screenshot from 2020-03-02 19-14-20](https://user-images.githubusercontent.com/16704297/75897205-df919780-5e40-11ea-959a-4681b872c7c1.png)
@horike37 I've added picture to show what exactly I want
