### ISSUE TITLE
Is it possible to have an api gateway request starting execution of state machine without defining the state machine 

### ISSUE THREAD

**Issue by zjyw** [serverless-operations/serverless-step-functions#309]
# This is a Question

## Description
Is it possible to have an api gateway request starting execution of state machine without defining the state machine instead I will pass the arn of the state machine in the input like?
{
    "stateMachineArn": "my state machine arn"
}
stepFunctions:
  stateMachines:
    hello:
      events:
        - http:
            path: posts/start
            method: POST
            action: StartExecution

For bug reports:
* What went wrong?
When I don't provide the definition, I got the following error:
```
  Type Error ---------------------------------------------
 
  Cannot read property 'States' of undefined
```

## Additional Data
* ***Serverless Framework Core Version you're using***:
1.45.1

* ***The Plugin Version you're using***:
2.17.1

**Comment by horike37** [comment]
Unfortunately, this is not supported and it would not  be introduced in the future since not fit core concept of this plugin
