### ISSUE TITLE
Logging to CloudWatch Logs from Step Functions

### ISSUE THREAD

**Issue by alexsavio** [serverless-operations/serverless-step-functions#335]
# This is a Question

I don't understand why in the documentation (and I am not able to) enable CloudWatch Logs for normal Step Functions (not Express Workflows).

It is possible to do it from the AWS console and with CloudFormation: https://docs.aws.amazon.com/step-functions/latest/apireference/API_CreateStateMachine.html

Why this plugin does not allow me to do it?

**Comment by theburningmonk** [comment]
@alexsavio yeah, it should be possible since #322 was merged a while back

**Comment by alexsavio** [comment]
Thanks a lot @theburningmonk. Maybe a change in the documentation could be done? Should I?

**Comment by theburningmonk** [comment]
please, much appreciated!
