### ISSUE TITLE
"DeletionPolicy": "Retain" for State Machine in CloudFormation template

### ISSUE THREAD

**Issue by DmytroKucheryavenko** [serverless-operations/serverless-step-functions#344]
## Proposal to add "retain" property to State Machine config

This feature could be useful for Blue-Green deployment when we do not want existing State Machine to be deleted after deploying the new one.

Pull request #343

**Comment by theburningmonk** [comment]
@DmytroKucheryavenko how are you generating a random logical ID for the state machine in this case?

**Comment by DmytroKucheryavenko** [comment]
@theburningmonk, okay let's clarify things: 
- different logical ID is generated only when State Machine name is changed, here is a function within`serverless-step-functions/lib/naming.js` that builds logical ID based on passed `stateMachineName` property: https://github.com/serverless-operations/serverless-step-functions/blob/24ed3018788552a059e216a4ac573372c973af80/lib/naming.js#L4
- Having State machine name as following
![Screen Shot 2020-06-16 at 11 20 13](https://user-images.githubusercontent.com/27201930/84750140-97e3e580-afc3-11ea-8027-1718a488d052.png)
  results into logical ID set to `MyStateMachineDashV1`. Changing name to `myStateMachine- 
  V2` will produce `MyStateMachineDashV2` etc.

- The main idea is to build name dynamically, CLI options suits well here
![Screen Shot 2020-06-16 at 11 37 26](https://user-images.githubusercontent.com/27201930/84751895-c5ca2980-afc5-11ea-9f1e-8446580e9b7a.png)
The same dynamically got property (myAppVersion in our case) can be used later to build qualified ARN for Lambda function:
![Screen Shot 2020-06-16 at 11 48 11](https://user-images.githubusercontent.com/27201930/84753295-7b49ac80-afc7-11ea-96ac-372931f70deb.png)

**Comment by theburningmonk** [comment]
@DmytroKucheryavenko right I see, so you actually change the name of the state machine, that was the missing piece. Now that makes sense.

**Comment by DmytroKucheryavenko** [comment]
@theburningmonk Is there a chance for PR #343 to be merged at some point ?

**Comment by theburningmonk** [comment]
@DmytroKucheryavenko I left a common on the PR last night, it looks good to me, if you can add some description of it in the README then it's good to go from my perspective.

**Comment by DmytroKucheryavenko** [comment]
@theburningmonk , will do

**Comment by DmytroKucheryavenko** [comment]
@theburningmonk ready
