### ISSUE TITLE
Move aws-sdk to devDependencies?

### ISSUE THREAD

**Issue by nampas** [serverless-operations/serverless-step-functions#347]
# This is a Feature Proposal

## Description

When serverless packages up a node project, it removes all devDependencies from the node_moduels directory. This is nice because dev dependencies can contain lots of heavyweight modules (e.g. TypeScript) that we don't want to bother shipping off to AWS.
Unfortunately, right now, serverless-step-functions brings in aws-sdk as a package dependency, which means that all ~50mb of that monster are package up and sent to AWS on each deploy. AWS includes aws-sdk in its nodejs runtime by default, so doing this is not necessary.

Can aws-sdk be made a dev dependency? That way any tests and local invocations of serverless will work fine, but will still allow serverless to remove aws-sdk automatically when packaging.

**Comment by nampas** [comment]
On that note, it'd also be worth removing serverless as a dependency entirely. The expectation is that serverless has already been installed globally

**Comment by theburningmonk** [comment]
@nampas in your project you should install plugins like `serverless-step-functions` as dev dependencies, so that when you package your functions none of it would get into your artefact.

**Comment by theburningmonk** [comment]
for example, [this project](https://github.com/theburningmonk/lambda-step-functions-demo)'s artefact is about 50kb, and it's only this big because of the `package-lock.json`

**Comment by theburningmonk** [comment]
@horike37 looking through the code, we don't actually require the `aws-sdk` anywhere, any idea why it's a dependency in the project at all?

**Comment by horike37** [comment]
@theburningmonk 
That was my careless mistake when the first release 😅 Should move to devDependencies.

**Comment by theburningmonk** [comment]
@horike37 we don't actually need the `aws-sdk`, right? can we remove it altogether?

**Comment by horike37** [comment]
Yup, right 🙆‍♂️

**Comment by nampas** [comment]
Hey thanks for the responses y'all. Happy to create a PR removing aws-sdk if you'd like.
