### ISSUE TITLE
Configuration error at root: unrecognized property 'stepFunctions'

### ISSUE THREAD

**Issue by TheEdgeOfCat** [serverless-operations/serverless-step-functions#355]
# This is a Bug Report

## Description

I'm getting a serverless configuration validation error when deploying with the step function plugin:

```
$ npx serverless deploy
Serverless: Configuration error at root: unrecognized property 'stepFunctions'
Serverless: If you prefer to not continue when error in configuration is approached, ensure `configValidationMode: error` in your config
Serverless: If errors are influenced by an external plugin, enquiry at plugin repository so schema extensions are added (https://www.serverless.com/framework/docs/providers/aws/guide/plugins#extending-validation-schema)
Serverless: If errors seem invalid, please report at https://github.com/serverless/serverless/issues/new?template=bug_report.md
Serverless: If you find this functionality problematic, you may turn it off with `configValidationMode: off` setting
```

## Additional Data
* ***Serverless Framework Core Version you're using***: 1.78.1
* ***The Plugin Version you're using***: 2.21.1
* ***Operating System***: Linux (node v14.7.0)

**Comment by theburningmonk** [comment]
@TheEdgeOfCat ooh, this is interesting, so the serverless framework started to do schema validation, that's new!

**Comment by TheEdgeOfCat** [comment]
Yes, Starting with [1.78.0](https://github.com/serverless/serverless/blob/master/CHANGELOG.md) :)

Maybe I should change this to a feature request instead? I'm not sure how you'd classify it. I could take a look into adding the schema, but probably not before Friday.

**Comment by theburningmonk** [comment]
If you could take a look and pull a PR together, that'd be great. Looks like there's a workaround for now anyway, by turning validation off.

**Comment by TheEdgeOfCat** [comment]
The validation is not enforced at this point anyway, so nothing is really broken. It's just an annoying red error that shows up as the first thing when you run `serverless deploy`
