### ISSUE TITLE
Support for maxconcurrency on Map state?

### ISSUE THREAD

**Issue by SanjayS5** [serverless-operations/serverless-step-functions#360]
# This is a question/feature proposal

Does this plugin already have support for this? If it does, could we have this added to the documentation please?
Cheers. 

## Description

For feature proposals:
* Step functions has a MaxConcurrency attribute that can be added to the map state:

From [AWS DOCS]( https://docs.aws.amazon.com/step-functions/latest/dg/amazon-states-language-map-state.html):

**MaxConcurrency (Optional)**

- The “MaxConcurrency”field’s value is an integer that provides an upper bound on how many invocations of the Iterator may run in parallel. For instance, a "MaxConcurrency" value of 10 will limit your Map state to 10 concurrent iterations running at one time.

**Comment by theburningmonk** [comment]
@SanjayS5 yup, it's already supported

**Comment by SanjayS5** [comment]
@theburningmonk Perfect, thank you for confirming. Closing this off :)
