### ISSUE TITLE
Need to extend schema validation for new serverless version

### ISSUE THREAD

**Issue by jdelsuc** [serverless-operations/serverless-step-functions#361]
# This is a Bug Report 

## Description

In version 1.78 we released our serverless.yml syntax validator schema to help catch errors created by accidentally formatting files incorrectly. As a part of that it means that plugin authors also needed to add additional details to the schema so that their plugin configurations are not flagged as an error

Thx

Julien

**Comment by TheEdgeOfRage** [comment]
I have added basic schema validation in #357 (#355 for reference), there just hasn't been a new release since then. 

What I've added is just the basic top level stepFunctions object and doesn't cover everything. It would be nice to also add complete schema validation.

**Comment by theburningmonk** [comment]
@TheEdgeOfRage ah I see what happened, I ran the release script the other day, but because the commit didn't follow conventional commit, semantic-release didn't pick it up as a new feature so skipped publishing. Let me see if I can force a new version

**Comment by theburningmonk** [comment]
that's published now as v2.22.0

**Comment by NevRA** [comment]
It works now. Thanks!
