### ISSUE TITLE
feat: add support for X-ray tracing

### ISSUE THREAD

**Issue by bryantbiggs** [serverless-operations/serverless-step-functions#373]
# This is a Feature Proposal

## Description

For feature proposals:
- It would be great to add support for enabling x-ray tracing to the plugin natively - new feature announced just yesterday https://aws.amazon.com/blogs/compute/introducing-aws-x-ray-new-integration-with-aws-step-functions/

**Comment by hassaku63** [comment]
It is able to enabling X-Ray by added tracingConfig parameter #374 , but I feel this is not enough as a feature to supports X-Ray.

In order to fully supports X-Ray, I think better to it need to adding a feature generate IAM Policy for StateMachine to use X-Ray  automatically.

**Comment by theburningmonk** [comment]
@hassaku63 fancy putting another PR to add the IAM permissions?

**Comment by hassaku63** [comment]
@theburningmonk yes, i'd like to submit another PR

**Comment by bryantbiggs** [comment]
thanks @hassaku63 and @theburningmonk for the quick response - I think those two PRs close out this issue :+1:
