### ISSUE TITLE
Add support for SageMaker Integration. Autogenerated IAM role throws exception.

### ISSUE THREAD

**Issue by siovaneDAZN** [serverless-operations/serverless-step-functions#385]
When trying to deploy the stepFunction with the sagemaker "TrainingJob" integration the following error is thrown:

```  mystepfunction-role-WOALXN3M2BWR' is not authorized to create managed-rule.  (Service: AWSStepFunctions; Status Code: 400; Error Code: AccessDeniedException; Request ID: {long-hex-code}; Proxy: null).```

The problem is that the following policy is required to be attached to the auto generated role linked to the step function:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "sagemaker:CreateTransformJob",
        "sagemaker:DescribeTransformJob",
        "sagemaker:StopTransformJob"
      ],
      "Resource": [
        "arn:aws:sagemaker:[[region]]:[[accountId]]:transform-job/[[transformJobName]]*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "sagemaker:ListTags"
      ],
      "Resource": [
        "*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iam:PassRole"
      ],
      "Resource": [
        "[[roleArn]]"
      ],
      "Condition": {
        "StringEquals": {
          "iam:PassedToService": "sagemaker.amazonaws.com"
        }
      }
    },
    {
      "Effect": "Allow",
      "Action": [
        "events:PutTargets",
        "events:PutRule",
        "events:DescribeRule"
      ],
      "Resource": [
        "arn:aws:events:[[region]]:[[accountId]]:rule/StepFunctionsGetEventsForSageMakerTransformJobsRule"
      ]
    }
  ]
}
```

As stated in the [AWS documentation](https://docs.aws.amazon.com/step-functions/latest/dg/sagemaker-iam.html#sagemaker-iam-createtrainingjob)

Potentially it could be defined separately and then attached to the step function with the `role:` field, but it would override the autogenerated iamrole making the function uneable to call the lambda functions linked to it.

I guess the role mentioned above needs to be attached to the autogenerated role at creation time.
Any work around on that?

**Comment by janyk** [comment]
Hey @siovaneDAZN - i've created a PR which I believe adds support for this, it's working for my state machine execution - I didn't need to add the statement for the sagemaker execution role - at least for my context.
