### ISSUE TITLE
Custom Cloudwatch alarms with serverless-plugin-aws-alerts

### ISSUE THREAD

**Issue by swilso793** [serverless-operations/serverless-step-functions#396]
# This is a Question

## Description

Hello, you mention in the documentation that it is possible to use alarms for the stepFunctions defined from the serverless-plugin-aws-alerts. How can i do that?

**Comment by theburningmonk** [comment]
@swilso793 have a look at their readme [here](https://github.com/ACloudGuru/serverless-plugin-aws-alerts) and see how you can define custom alarms. If you need to know the namespace and name of the metrics, then please refer to [this page](https://docs.aws.amazon.com/step-functions/latest/dg/procedure-cw-metrics.html), or it might be easier to run your state machine a few times and then find the metrics in the CloudWatch console.

**Comment by swilso793** [comment]
Thanks 👍
