### ISSUE TITLE
Travis-CI integration broken

### ISSUE THREAD

**Issue by danrivett** [serverless-operations/serverless-step-functions#444]
# This is a Bug Report

## Description

PRs are no longer being automatically built (e.g #443) and a quick investigation looks like the CI pipeline needs to be migrated to travis-ci.com as it's currently using travis-ci.org, and [it's showing the following message](https://travis-ci.org/github/serverless-operations/serverless-step-functions):

> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on. 

<img width="1699" alt="Screen Shot 2021-07-02 at 6 38 13 AM" src="https://user-images.githubusercontent.com/30873208/124283009-4770f480-db00-11eb-892d-997a9d67f86c.png">

**Comment by horike37** [comment]
Thank you for reporting.
I just moved to GitHub Actions.
