### ISSUE TITLE
Integration with Serverless Framework v3

### ISSUE THREAD

**Issue by mnapoli** [serverless-operations/serverless-step-functions#465]
Hi 👋 , Serverless Framework core team here!

We're working on the v3 beta version right now. The v3 will include a redesigned CLI output:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/720328/139266855-7c0c15e1-9201-48b6-92f0-db6af2da4d11.png">

You can try the v3 beta with: `npm i serverless@pre-3`

To help plugins integrate with that new design (and build a great user experience), we've added new APIs for plugins:

- [Video introduction (Youtube)](https://www.youtube.com/watch?v=K3IhZ9fImk4)
- [Documentation of the new API](https://www.serverless.com/framework/docs/guides/plugins/cli-output)

Any feedback is appreciated! If you want to update the serverless-step-functions plugin to use these new APIs, feel free to ping me if you have any questions!

If you don't have time to update the plugin, let me know, we can send a pull request!

**Comment by horike37** [comment]
Thank you for letting us know! v3 has been supported in the latest plugin version!

**Comment by mnapoli** [comment]
Great, thanks for the update!

Just to be sure I understand, did you also update logs written by the plugin to use the new APIs/match the new design?

**Comment by horike37** [comment]
I haven't done it yet. What does that something like? Can you share the details?

**Comment by mnapoli** [comment]
Sure! Here is a blog post that introduces it: https://www.serverless.com/blog/serverless-framework-v3-beta

Also as mentioned in the issue above, here is more information about the new API:

- [documentation of the new API](https://www.serverless.com/framework/docs/guides/plugins/cli-output)
- [quick video introduction (Youtube)](https://www.youtube.com/watch?v=K3IhZ9fImk4)

Does that help a bit?

**Comment by horike37** [comment]
Thank you for providing the documentation. I'll take a look and update.

**Comment by horike37** [comment]
@mnapoli 
This has been shipped in the latest version.
Thanks!
