### ISSUE TITLE
Upgrade serverless peer dependency to v4

### ISSUE THREAD

**Issue by threes-was-taken** [serverless-operations/serverless-step-functions#614]
# This is a Feature Proposal

## Description

Since Serverless V4 became generally available since June 13th, I'd like to see the serverless peer dependency upgraded to accept v4.

* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.  
  * Allow users of this lib to use the latest version of serverless.

**Comment by fernandohonig** [comment]
Hi, any progress here? I can't upgrade to sls4 until this is merged. Thanks
